# Generated by Django 5.2.11 on 2026-03-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.CharField(choices=[('1', 'Hour 1'), ('2', 'Hour 2'), ('3', 'Hour 3'), ('4', 'Hour 4'), ('5', 'Hour 5'), ('6', 'Hour 6')], max_length=10)),
                ('module', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
            ],
        ),
    ]
