# Generated by Django 5.2.11 on 2026-03-03 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_timeslot_period'),
        ('faculty', '0002_coursediary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursediary',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
