# Generated by Django 5.2.11 on 2026-03-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_coursediary_faculty_delete_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursediary',
            name='faculty',
            field=models.IntegerField(),
        ),
    ]
