# Generated by Django 5.2.7 on 2025-10-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_timeslot_timetableentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='period',
            field=models.IntegerField(choices=[(1, 'P1'), (2, 'P2'), (3, 'P3'), (4, 'P4'), (5, 'P5'), (6, 'P6')]),
        ),
    ]
